### ISSUE TITLE
UDP not working when deployed on a remote host (VPS)

### ISSUE THREAD

**Issue by entelostre** [tom-weiland/tcp-udp-networking#15]
I have added the required port in iptables like:
```
sudo iptables -A INPUT -p udp -m udp --dport 26950 -j ACCEPT
sudo iptables -A OUTPUT -p udp -m udp --dport 26950 -j ACCEPT
```
any ideas? thanks in advance

**Comment by tom-weiland** [comment]
Who are you using as your host? I haven't really looked into hosting much myself, so I'm not sure I'll be able to help here...

**Comment by entelostre** [comment]
I am using a Debian VPS by a company called Contabo

**Comment by orrburgel** [comment]
Could be really interesting to try and run this on linux too no?

**Comment by tom-weiland** [comment]
> I am using a Debian VPS by a company called Contabo.
> I can see the udp packets arriving to server in port 26950 but it seems that they aren't visible to the application.

Are the ports opened properly (for TCP _and_ UDP)? The packets could be getting blocked by firewall too—if that's not it then I'm not sure how else to help, but this doesn't really sound like an issue with the code itself (which is why I'm going to close this for now).

Maybe get in touch with their customer service?
