### ISSUE TITLE
Encrypted packets

### ISSUE THREAD

**Issue by Oisann** [tom-weiland/tcp-udp-networking#5]
Hi, I commented on your latest video about encryption.

As I said in that comment, I have a working solution for TCP, however it doesn't really work for UDP.
My plans are to do something different for our game, and just have an additional transport layer. Secure TCP, TCP and UDP.

If you want I can try to create a pull request with the same changes that I have. Maybe someone from your discord have some better ideas and/or a solution to the UDP issue I am seeing.

To add basic support for it in TCP, not that many lines of code is required. However I also did some changes to try to stop replay attacks. It's not very complicated either, just not very pretty at the moment. Since I decided to use AES, there are some obvious issues that could be encountered as well, so I will try to document why some of the things are the way they are.

I will have to spend some time to adopt it to this repo (we also only use the console server). I probably should make sure I change it for both here. Let me know if you think this is just a waste of time, or if it could help. Since you helped me finally getting a proper Server-Client boilerplate going, I feel like I should give something back :)

**Comment by tom-weiland** [comment]
Which video are you referring to? I haven't made one about encryption at this point, largely because it's not something I've actually tackled myself...

If you want to adapt your code to work with this repo you're certainly welcome to, however I don't plan on adding large amounts of external code, as this repo is meant to mirror the tutorial series as it progresses.

If you're concerned about giving back, helping others on Discord is another way of doing it, but if you do adapt your code, I'd definitely take a look at it (and maybe take some inspiration from it)!

**Comment by Oisann** [comment]
Sorry, I made a comment about encryption on your latest video... :D

**Comment by Oisann** [comment]
I didn't mean for you to have to integrate it, but maybe it could be useful to see in this projects context.

**Comment by tom-weiland** [comment]
In that case, I would have read your comment, although I must admit I don't remember. Seeing it in this context would probably be useful, yes.

**Comment by orrburgel** [comment]
Hey, May I get a link to your fork? I'm new to GitHub sorry I have no idea how to find your pull request
