### ISSUE TITLE
Crashing NetCore Version

### ISSUE THREAD

**Issue by devgodstudio** [tom-weiland/tcp-udp-networking#6]
Howdy, 

I followed your tutorial and then downloaded your files here.
I replaced my project clientside with yours and server side with yours. 

While I am able to run the unity version of the server without crashes and I am getting a crash with the netcore version.

If I attempt to move I get a key error has to the with the packet dictionary I believe I will attempt to fix it myself but not familiar with netcore.. usually I would use framework.

![image](https://user-images.githubusercontent.com/52840649/79717988-0731a780-82a9-11ea-8ecc-822aace36bbe.png)

**Comment by tom-weiland** [comment]
Which branch did you grab the project from? You'll run into issues if you use the client from branch 6 and up with the console server because part 5 of my tutorial series was the last time we modified it.

**Comment by lihuaweishiyigehaoren** [comment]
> Howdy,
> 
> I followed your tutorial and then downloaded your files here.
> I replaced my project clientside with yours and server side with yours.
> 
> While I am able to run the unity version of the server without crashes and I am getting a crash with the netcore version.
> 
> If I attempt to move I get a key error has to the with the packet dictionary I believe I will attempt to fix it myself but not familiar with netcore.. usually I would use framework.
> 
> ![image](https://user-images.githubusercontent.com/52840649/79717988-0731a780-82a9-11ea-8ecc-822aace36bbe.png)

I have the same question,have you sloved it?

**Comment by tom-weiland** [comment]
> I have the same question,have you sloved it?
Again, which branch did you grab the project from? As I said before, "you'll run into issues if you use the client from branch 6 and up with the console server."

The console server _will not work_ with the client project from the tutorial-part6 branch and up. In part 6 of my tutorial series we move the server project into Unity, and from that point on we _only_ make changes in the Unity server.

The key KeyNotFoundExceptions are occurring because the client is sending packets which the console server doesn't recognize. Either use the Unity server or grab the project from the tutorial-part5 branch.
